# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0006_merge_20161207_1442'),
        ('GroupsApp', '0006_merge_20161207_1504'),
    ]

    operations = [
    ]
