# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0003_auto_20161202_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectsApp.projectTag'),
        ),
    ]
