# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0004_auto_20161206_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tag',
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='ProjectsApp.projectTag'),
        ),
    ]
