# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0006_auto_20161206_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttag',
            name='tagtype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
