# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsApp', '0002_auto_20161207_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
