# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0002_auto_20161128_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='about',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
