# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0002_myuser_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='university_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
    ]
