# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0003_auto_20161127_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
