# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0004_myuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_associated_professor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='office',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
